services:
  myapp:
    image: myapp:1
    container_name: myapp_container
    ports:
      - "8080:5000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: myapp_db
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    tmpfs:
      - /var/lib/postgresql/data  # No volume, data is ephemeral
    restart: always

secrets:
  db_password:
    file: ./secrets/db_password.txt
